import type { PullRequestDraft } from "./types";
import { clip, normalizeWhitespace, slugSegment, stableHash } from "./utils";

function shortSummary(prompt: string, maxLength = 60): string {
  return clip(normalizeWhitespace(prompt), maxLength);
}

export function fallbackBranchName(prompt: string): string {
  const baseSlug = slugSegment(prompt)
    .split("-")
    .filter(Boolean)
    .slice(0, 6)
    .join("-");
  const slug = baseSlug || "update";

  return `feature/${clip(slug, 36).replace(/\.\.\.$/, "")}-${stableHash(prompt, 6)}`;
}

export function fallbackCommitMessage(
  prompt: string,
  mode: "implementation" | "review",
): string {
  const summary = shortSummary(prompt, 50);

  if (mode === "review") {
    return `fix: address review feedback for ${summary}`;
  }

  return `feat: implement ${summary}`;
}

export function fallbackPullRequestDraft(
  prompt: string,
  branch: string,
  baseBranch: string,
): PullRequestDraft {
  const summary = shortSummary(prompt, 72);

  return {
    title: `feat: ${summary}`,
    body: [
      "## Summary",
      `- Requested change: ${summary}`,
      `- Head branch: \`${branch}\``,
      `- Base branch: \`${baseBranch}\``,
      "",
      "## Notes",
      "- Generated by the deterministic Bun Codex harness.",
    ].join("\n"),
  };
}
