import type { PullRequestDraft } from "./types";
import { clip, normalizeWhitespace, stableHash } from "./utils";

function slugSegment(value: string): string {
  const ascii = Array.from(value.normalize("NFKD"))
    .filter((character) => character.charCodeAt(0) <= 0x7f)
    .join("");

  return ascii
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function shortSummary(prompt: string, maxLength = 60): string {
  return clip(normalizeWhitespace(prompt), maxLength);
}

export function fallbackBranchName(prompt: string): string {
  const baseSlug = slugSegment(prompt)
    .split("-")
    .filter(Boolean)
    .slice(0, 6)
    .join("-");
  const slug = baseSlug || "update";

  return `feature/${clip(slug, 36).replace(/\.\.\.$/, "")}-${stableHash(prompt, 6)}`;
}

export function fallbackCommitMessage(
  prompt: string,
  mode: "implementation" | "review",
): string {
  const summary = shortSummary(prompt, 50);

  if (mode === "review") {
    return `fix: address review feedback for ${summary}`;
  }

  return `feat: implement ${summary}`;
}

export function fallbackPullRequestDraft(
  prompt: string,
  branch: string,
  baseBranch: string,
): PullRequestDraft {
  const summary = shortSummary(prompt, 72);

  return {
    title: `feat: ${summary}`,
    body: [
      "## Summary",
      `- Requested change: ${summary}`,
      `- Head branch: \`${branch}\``,
      `- Base branch: \`${baseBranch}\``,
      "",
      "## Notes",
      "- Generated by the deterministic Bun Codex harness.",
    ].join("\n"),
  };
}

export function coerceBranchName(value: string): string {
  const trimmed = value.trim().split(/\r?\n/, 1)[0] ?? "";
  const normalized = trimmed
    .replace(/^refs\/heads\//, "")
    .replace(/[^A-Za-z0-9/_-]+/g, "-")
    .replace(/\/+/g, "/")
    .replace(/-+/g, "-")
    .replace(/(^[/.]+|[/.]+$)/g, "");

  return normalized;
}

export function parseDraftResponse(output: string): PullRequestDraft | null {
  const normalized = output.replace(/\r\n/g, "\n").trim();
  const titleMatch = normalized.match(/^TITLE:\s*(.+)$/m);
  const bodyMatch = normalized.match(/^BODY:\s*([\s\S]*)$/m);

  if (!titleMatch || !bodyMatch) {
    return null;
  }

  return {
    title: titleMatch[1]?.trim() ?? "",
    body: bodyMatch[1]?.trim() ?? "",
  };
}
